StadiumManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stadium.urls')),
    path('', include('stadium.urls2')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

stadium/urls.py
from django.contrib import admin
from django.urls import path
from  .views import *

urlpatterns = [
    path('',home, name='home'),
    path('login/', sign_in, name='login'),
    path('register/', register, name='register'),
    path('edit_user/<int:pid>/',register,name="edit_user"),
    path('edit_game/<int:pid>/',Add_Game,name="edit_game"),
    path('register2/', register2, name='register2'),
    path('edit_user2/<int:pid>/',register2,name="edit_user2"),
    path('delete_user/<int:pid>/',delete_user,name="delete_user"),
    path('delete_book/<int:pid>/',delete_book,name="delete_book"),
    path('delete_game/<int:pid>/',delete_game,name="delete_game"),
    path('delete_category/<int:pid>/',delete_category,name="delete_category"),
    path('change_contact_status/<int:pid>/',change_contact_status,name="change_contact_status"),
    path('change_status/<int:pid>/',change_status,name="change_status"),
    path('change_game_category/<int:pid>/',add_game_category,name="change_game_category"),
    path('add_game_category/',add_game_category,name="add_game_category"),
    path('logout/', Logout, name='logout'),
    path('profile/', Single_Profile, name='profile'),
    path('add_game/',Add_Game, name='add_game'),
    path('book_ticket/<int:gid>/',book_ticket, name='book_ticket'),
    path('my_book/',my_book, name='my_book'),
    path('view_book/',view_booking, name='view_booking'),
    path('view_contact/',view_contact, name='view_contact'),
    path('view_contact_unread/',view_contact_unread, name='view_contact_unread'),
    path('new_user/',new_booking, name='new_booking'),
    path('all_user/',total_registered_user, name='total_registered_user'),
    path('view_game/',view_game, name='view_game'),   
    path('view_game_category/',view_game_category, name='view_game_category'),   
    path('search_between_dates/',search_between_dates, name='search_between_dates'),
    path('user_feedback/',user_feedback, name='user_feedback'),
    path('feedback_unread/',feedback_unread, name='feedback_unread'),
    path('change_FeedBack_status/<int:pid>/',change_FeedBack_status,name="change_FeedBack_status"),
    path('feedback_read/',feedback_read, name='feedback_read'),
       
]

stadium/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import IntegerField
from django.db.models.lookups import Transform

# Create your models here.
class Stadium_Profile(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null = True)
    contact_no = models.CharField(max_length=1000,null = True)
    address = models.CharField(max_length=1000,null = True)
    city = models.CharField(max_length=1000,null =True)
    images = models.FileField(null=True)
    created  = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True, null=True)
    
    def __str__(self):
        return(self.user.username)

STATUS_FEEDBACK = ((1, 'Read'), (2, "UnRead"))
class Feedback(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null = True, blank=True)
    description = models.CharField(max_length=5000,null=True)
    created  = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True, null=True)
    feedback_status = models.IntegerField(choices=STATUS_FEEDBACK , null = True, blank=True,default=2)
    
    def __str__(self):
        return self.user.username
    

class GameCategory(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name

class Game(models.Model):
    category = models.ForeignKey(GameCategory, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null = True, blank=True)
    game_name = models.CharField(max_length=100, null=True, blank=True)
    stadium_name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    total_seats = models.IntegerField(null=True, blank=True)
    local_seats = models.IntegerField(null=True, blank=True)
    vip_seats = models.IntegerField(null=True, blank=True)
    local_seats_price = models.IntegerField(null=True, blank=True)
    vip_seats_price = models.IntegerField(null=True, blank=True)
    remaining_seats = models.IntegerField(null=True, blank=True)
    last_booking = models.DateField(null=True, blank=True)
    game_date = models.DateField(null=True, blank=True)
    game_time = models.TimeField(null=True, blank=True)
    created  = models.DateField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)
    active = models.BooleanField(default=True, null=True)
    image = models.FileField(null = True)

    def __str__(self):
        return self.game_name


SEATS_CATEGORY = ((1, "VIP"), (2, "Local"))
STATUS = ((1, 'Pending'), (2, "Accepted"), (3, 'Canceled'))
class Booking(models.Model):
    status = models.IntegerField(choices=STATUS, null=True, blank=True, default=1)
    booking_id = models.CharField(max_length=100,null=True, blank=True)
    game = models.ForeignKey(Game,on_delete=models.CASCADE,null = True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null = True, blank=True)
    seat_choices = models.IntegerField(choices=SEATS_CATEGORY, null=True, blank=True)
    booking_for = models.DateField(null=True, blank=True)
    total_seats = models.CharField(max_length=100, null=True, blank=True)
    total_price = models.IntegerField(null=True, blank=True)
    created  = models.DateField(auto_now_add=True, null=True)
    updated = models.DateField(auto_now=True, null=True)

    def __str__(self) -> str:
        return self.game.game_name
    
    
STATUS_CONTACT = ((1, 'Read'), (2, "UnRead"))
class Contact(models.Model):
    created = models.DateField(auto_now_add=True, null = True)
    contact_no = models.CharField(max_length=15, null = True)
    first_name = models.CharField(max_length=100,null=True)
    last_name = models.CharField(max_length=100,null=True)
    email = models.CharField(max_length=100,null=True)
    address = models.CharField(max_length=1000,null=True)
    description = models.CharField(max_length=2000,null=True)
    contact_status = models.IntegerField(choices=STATUS_CONTACT , null = True, blank=True,default=2)
    
    def __str__(self) -> str:
        return self.first_name 
    

    

    

stadium/forms.py
from django import forms
from django.db.models import fields 
from .models import *

class RegisterForm(forms.ModelForm):
    class Meta:
        model= Stadium_Profile
        exclude= ('user','created','updated')
        
class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        exclude = ('user','created','updated', 'remaining_seats')

class GameCategoryForm(forms.ModelForm):
    class Meta:
        model = GameCategory
        fields = ['name', 'image']
        
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        exclude = ('user','created','updated')
        
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact 
        exclude = ('created','contact_status')  
        
class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ('user','created','updated')
        

stadium/views.py
# from django.db.models.expressions import Random
from django.shortcuts import render, redirect 
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from .models import *
from django.contrib import messages
import datetime 
from django.contrib.auth.decorators import login_required
import random

# Create your views here.
def home(request):
    game = Game.objects.all()
    feedback = Feedback.objects.all()
    game_cat = GameCategory.objects.all() 
    book_all = Booking.objects.all()
    newbooking = Booking.objects.filter(status=1).count()
    stadium = Stadium_Profile.objects.all() 
    d = {'game_cat':game_cat.count(), 'game': game.count(),'newbooking':newbooking, 'book':book_all.count(),'total_user':stadium.count(), 'game_data':game.order_by('-id')[0:4],'feedback_data':feedback.order_by('-id')[0:10]}
    return render(request,'carousel.html', d)

def register(request,pid=None):
    profile = None
    user = None
    if pid:
        user = User.objects.get(id=pid)
        profile = Stadium_Profile.objects.get(user=user)
    if request.method=='POST':
        form = RegisterForm(request.POST,request.FILES,instance=profile) #matching stadium profile attributes 
        fname = request.POST['first_name']
        lname = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        if form.is_valid():
            new_profile = form.save()
            if not profile:
                password = request.POST['password']
                user = User.objects.create_user(first_name=fname,last_name=lname,username=username,email=email,password=password)
                new_profile.user = user
                messages.success(request, "Registration successfully")
                new_profile.save() 
                return redirect('login')
            else:
                user.first_name = fname
                user.last_name = lname
                user.email = email
                user.save()
                profile.user=user 
                profile.save()
                messages.success(request, "Updated successfully")
                return redirect('profile') 
        else:
            print(form.errors)
    d ={'profile':profile}
    return render(request,'register.html',d)

def register2(request,pid=None):
    profile = None
    user = None
    if pid:
        user = User.objects.get(id=pid)
        profile = Stadium_Profile.objects.get(user=user)
    if request.method=='POST':
        form = RegisterForm(request.POST,request.FILES,instance=profile) #matching stadium profile attributes 
        fname = request.POST['first_name']
        lname = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        if form.is_valid():
            new_profile = form.save()
            if not profile:
                password = request.POST['password']
                user = User.objects.create_user(first_name=fname,last_name=lname,username=username,email=email,password=password)
                new_profile.user = user
                new_profile.save()
                messages.success(request, "Registration successfully")
                return redirect('login')
            else:
                user.first_name = fname
                user.last_name = lname
                user.email = email
                user.save()
                profile.user=user 
                messages.success(request, "Updated successfully")
                profile.save()
                return redirect('total_registered_user')  
        else:
            print(form.errors)
    d ={'profile':profile}
    return render(request,'Admintemplates/register2.html',d)
        

def sign_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username,password=password) #check the exixting user
        if user.is_staff:
            login(request,user)
            messages.success(request, "Logged in successfully")
            return redirect('home_index')
        elif user:
            login(request,user)
            messages.success(request, "Logged in successfully")
            return redirect('home')
        else:
            messages.success(request, "Username and Password are invalid.")
    return render(request,'login.html')
        
@login_required(login_url='/login/')
def Single_Profile(request):  #get single data 
    single_data = Stadium_Profile.objects.get(user=request.user)
    dict = {
        'data':single_data
    }
    return render(request,'profile.html',dict)

@login_required(login_url='/login/')
def All_Profile(request):  # getmultiple data
    single_data = Stadium_Profile.objects.all()
    dict = {
        'data':single_data
    }
    return render(request,'contact.html',dict)

@login_required(login_url='/login/')
def delete_user(request,pid):
    profile = Stadium_Profile.objects.get(id = pid)
    profile.delete()
    messages.success(request, "Deleted successfully")
    return redirect('total_registered_user')

@login_required(login_url='/login/')
def delete_book(request,pid):
    profile = Booking.objects.get(id = pid)
    profile.delete()
    messages.success(request, "Deleted successfully")
    return redirect('view_booking')

@login_required(login_url='/login/')
def Logout(request):
    messages.success(request, "Logout Successfully")
    logout(request)
    return redirect('home')

@login_required(login_url='/login/')
def Add_Game(request,pid=None):
    game_cat = GameCategory.objects.all()
    game = None
    if pid:
        game = Game.objects.get(id=pid)
    if request.method == 'POST':
        form = GameForm(request.POST,request.FILES,instance=game)
        if form.is_valid():
            new_game = form.save()
            #new_game.remaining_seats = 80
            new_game.user = request.user
            if not pid:
                new_game.remaining_seats = new_game.total_seats
                messages.success(request, "Added successfully")
            else:
                messages.success(request, "Updated successfully")
            new_game.save()
            #messages.success(request, "Added successfully")
            return redirect('view_game')
    d = {'game':game, 'category':game_cat}
    return render(request,'add_game.html',d)
 
@login_required(login_url='/login/')          
def book_ticket(request,gid, pid=None):
    game = Game.objects.get(id=gid)
    book_ticket = None
    if pid:
        book_ticket = Booking.objects.get(id=pid)
    if request.method == 'POST':
        form = BookingForm(request.POST,request.FILES,instance=book_ticket)
        if form.is_valid():
            new_booking = form.save()     
            new_booking.user = request.user
            new_booking.status = 1
            random_number = 0
            while(1):
                random_number = random.randint(1000000000, 9999999999)
                try:
                    Booking.objects.get(booking_id = random_number)
                except:
                    new_booking.booking_id = random_number
                    new_booking.save()
                    break
            new_booking.game.remaining_seats -= int(request.POST.get('total_seats'))
            new_booking.save()
            new_booking.game.save()
            messages.success(request, "Booked successfully")
            return redirect('my_book')
        else:
            print(form.errors)
    d = {'book_ticket':book_ticket, 'seat':SEATS_CATEGORY, 'game':game}
    return render(request, 'book.html',d)

@login_required(login_url='/login/')              
def my_book(request):
    book =  Booking.objects.filter(user=request.user)
    return render(request, 'my_booking.html',{'book':book})

@login_required(login_url='/login/')
def view_booking(request):
    view_book = Booking.objects.all()
    if request.method == "POST":
        search = request.POST['search']
        view_book = view_book.filter(booking_id=search)
    return render(request, 'Admintemplates/view_booking.html',{'view_book':view_book})
   
@login_required(login_url='/login/')    
def new_booking(request):
    new_book = Booking.objects.filter(status=1)
    return render(request, 'Admintemplates/new_booking.html',{'new_user':new_book})

@login_required(login_url='/login/')
def total_registered_user(request):
    all_user = Stadium_Profile.objects.all()
    return render(request, 'Admintemplates/total_registered_user.html',{'all_profile_registered':all_user})

@login_required(login_url='/login/')
def view_game(request):
    v_game = Game.objects.all()
    return render(request, 'Admintemplates/view_game.html',{'game_info':v_game})

@login_required(login_url='/login/')
def change_status(request, pid):
    book = Booking.objects.get(id = pid)
    if request.user.is_staff:
        if book.status == 1:
            book.status = 2
            book.save()
        elif book.status == 2:
            book.status = 1
            book.save()
        messages.success(request, "Status changed successfully")
        return redirect('view_booking')
    else:
        book.status = 3
        book.save()
        messages.success(request, "Status changed successfully")
        return redirect('my_book') 

@login_required(login_url='/login/')
def delete_game(request,pid):
    game = Game.objects.get(id=pid)
    game.delete()
    messages.success(request, "Deleted successfully")
    return redirect("view_game")

@login_required(login_url='/login/')
def delete_category(request,pid):
    game = GameCategory.objects.get(id=pid)
    game.delete()
    messages.success(request, "Deleted successfully")
    return redirect("view_game_category")

@login_required(login_url='/login/')
def add_game_category(request, pid=None):
    game_cat = None
    if pid:
        game_cat = GameCategory.objects.get(id=pid)
    if request.method == "POST":

stadium/templates/login.html
{% extends 'index.html' %}
{% load static %}
{% block body %}

<div class="agile_about contact" id="contact">

		<div class="agileits_agile_contact_form">
			<h3>Login</h3>
										
	<div class="container">	
			<div class="agileits_agile_about_mail">
				<form action="" method="post">
                {% csrf_token %}
                <div class="row">
					<div class="col-md-12 agileits_agile_about_mail_left">
						<input type="text" name="username" placeholder="Username" required="">
					<div class="clearfix"> </div>
					</div>
				</div>
                <div class="row">
					<div class="col-md-12 agileits_agile_about_mail_left">
						<input type="password" name="password" placeholder="Password" required="">
					<div class="clearfix"> </div>
					</div>
				</div>
				
					<div class="submit pull-right" style="margin-top:10px;margin-right:3%;margin-bottom:10%">
						<input type="submit" value="Submit">
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

stadium/templates/table_js.html
<script>
    $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.1/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.0/css/buttons.dataTables.min.css">

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js"> </script>

<div class="agileits_agile_contact_form">
<br>
    <h3>Booking Details</h3>
<div class="container">
<table id="example" class="display table" style="width:100%">
        <thead class="table-light">
            <tr>
                <th>BookingID</th>
                <th>Game</th>
                <th>Booking Date</th>
                <th>Booking For</th>
                <th>Total Seats</th>
                <th>Total Price</th>
                <th>Seat Type</th>
                <th>Status</th>
                <th>Action</th>

            </tr>
        </thead>
        <tbody>
            {% for i in book %}
            <tr>
                <td>{{i.booking_id}}</td>
                <td>


<a href="#" data-toggle="modal" data-target="#tyModal-{{forloop.counter}}">{{i.game.game_name}}</a>


<div id="tyModal-{{forloop.counter}}" style="width:100%" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Game Information</h4>
      </div>
      <div class="modal-body">
        <table>
            <tr>
                <th>Game Name</th>
                <td style="width:25%">{{i.game.game_name}}</td>
                <th>Game image</th>
                <td style="width:25%"><img src="{{i.game.image.url}}" style="width:100px;height:80px"/></td></td>
            </tr>

            <tr style="height:30px">
                <th>Total Seats</th>
                <td style="width:25%">{{i.game.total_seats}}</td>
                <th>Available Seats</th>
                <td style="width:25%">{{i.game.remaining_seats}}</td>
            </tr>

            <tr style="height:30px">
                <th>Vip Seats Price</th>
                <td style="width:25%">{{i.game.vip_seats_price}}</td>
                <th>Local Seats Price</th>
                <td style="width:25%">{{i.game.local_seats_price}}</td>
            </tr>


            <tr style="height:30px">
                <th>Last Booking</th>
                <td style="width:25%">{{i.game.last_booking}}</td>
                <th> Game Date</th>
                <td style="width:25%">{{i.game.game_date}}</td>
            </tr>

            <tr style="height:30px">
                <th>Description</th>
                <td style="width:25%">{{i.game.description}}</td>
            </tr>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
</td>
                <td>{{i.created}}</td>
                <td>{{i.booking_for}}</td>
                <td>{{i.total_seats}}</td>
                <td>{{i.total_price}}</td>
                <td>{{i.get_seat_choices_display}}</td>  
                <td>{{i.get_status_display}}</td>  
                <td>{% if i.status != 3 %}<button class="btn btn-danger"><a href="/change_status/{{i.id}}/" onclick="return confirm('Do you want to Cancel your booking.')" style="color:white">Cancel</a></button>{% else %}------{% endif %}</td> 

            </tr>
            {% empty %}

            <tr>
            <td colspan="8">Data Not Found</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>BookingID</th>
                <th>Game</th>
                <th>Booking Date</th>
                <th>Booking For</th>
                <th>Total Seats</th>
                <th>Total Price</th>
                <th>Seat Type</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </tfoot>
    </table>
    </div>
    </div>

stadium/templates/view_contact.html
{% extends 'Admintemplates/index.html' %}
{% load static %}
{% block body %}  

<script>
    $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.1/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.0/css/buttons.dataTables.min.css">

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js"> </script>

<div class="container">	
	<div id="page-wrapper">
			<div class="main-page">
				<div class="forms">
					<h2 class="title1"></h2>
					<div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
						<div class="form-title">
							<h4>Read Enquiry</h4>
						</div>

<table id="example" class="display table" style="width:100%">
        <thead class="table-light">
            <tr>
                <th>First Name</th>
                <th>Last Name </th>
                <th>Email</th>
                <th>Contact NO</th>
                <th>Address</th>
                <th>Contact Status</th>
                <th>Action</th>

            </tr>
        </thead>
        <tbody>
            {% for i in contact_info %}
            <tr>
                <td>{{i.first_name}}</td>
                <td>{{i.last_name}}</td>
                <td>{{i.email}}</td>
                <td>{{i.contact_no}}</td>
                <td>{{i.address}}</td>
                <td>{{i.get_contact_status_display}}</td>
                <td><button  class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal-{{forloop.counter}}"><a href="#" style = "color: white">View_Message</a></button></td>

            <!-- Modal -->
            <div id="myModal-{{forloop.counter}}" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">View Description</h4>
                </div>
                <div class="modal-body">
                    <p>{{i.description}}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
                </div>

            </div>
            </div>

            </tr>
            {% empty %}

            <tr>
            <td colspan="8">Data Not Found</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>First Name</th>
                <th>Last Name </th>
                <th>Email</th>
                <th>Contact NO</th>
                <th>Address</th>
                <th>Contact Status</th>
                <th>Action</th>
            </tr>
        </tfoot>
    </table>

    <!-- Trigger the modal with a button -->



    </div>
    </div>
    </div>
    </div>
    </div>


{% endblock %}

stadium/templates/view_contact_unread.html
{% extends 'Admintemplates/index.html' %}
{% load static %}
{% block body %}  

<script>
    $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.1/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.0/css/buttons.dataTables.min.css">

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js"> </script>

<div class="container">	
	<div id="page-wrapper">
			<div class="main-page">
				<div class="forms">
					<h2 class="title1"></h2>
					<div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
						<div class="form-title">
							<h4>Unread Enquiry</h4>
						</div>

<table id="example" class="display table" style="width:100%">
        <thead class="table-light">
            <tr>
                <th>First Name</th>
                <th>Last Name </th>
                <th>Email</th>
                <th>Contact NO</th>
                <th>Address</th>
                <th>Contact Status</th>
                <th>Action</th>

            </tr>
        </thead>
        <tbody>
            {% for i in contact_info %}
            <tr>
                <td>{{i.first_name}}</td>
                <td>{{i.last_name}}</td>
                <td>{{i.email}}</td>
                <td>{{i.contact_no}}</td>
                <td>{{i.address}}</td>
                <td>{{i.get_contact_status_display}}</td>
                <td><button  class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal-{{forloop.counter}}"><a href="#" style = "color: white">View_Message</a></button></td>

            <!-- Modal -->
            <div id="myModal-{{forloop.counter}}" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                <div class="modal-header">
                    <a href="{% url 'change_contact_status' i.id %}">
                        <button type="button" class="close">&times;</button>
                    </a>
                    <h4 class="modal-title">View Description</h4>
                </div>
                <div class="modal-body">
                    <p>{{i.description}}</p>
                </div>
                <div class="modal-footer">
                    <a href="{% url 'change_contact_status' i.id %}">
                        <button type="button" class="btn btn-default">Close</button>
                    </a>
                </div>
                </div>

            </div>
            </div>

            </tr>
            {% empty %}

            <tr>
            <td colspan="8">Data Not Found</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>First Name</th>
                <th>Last Name </th>
                <th>Email</th>
                <th>Contact NO</th>
                <th>Address</th>
                <th>Contact Status</th>
                <th>Action</th>
            </tr>
        </tfoot>
    </table>

    </div>
    </div>
    </div>
    </div>
    </div>


{% endblock %}